[window]
padding = { x = 0, y = 0 }
dynamic_padding = false
opacity = 0.94
blur = true
decorations = "None"

[scrolling]
history = 10000
multiplier = 3

[font]
size = 11.0
offset = { x = 0, y = 1 }

[font.normal]
family = "JetBrainsMono Nerd Font"
style = "Regular"
[font.bold]
family = "JetBrainsMono Nerd Font"
style = "Bold"
[font.italic]
family = "JetBrainsMono Nerd Font"
style = "Italic"

[cursor]
style = { shape = "Block", blinking = "On" }
blink_interval = 600

[colors.primary]
background = "#1d2021"
foreground = "#ebdbb2"
[colors.cursor]
text = "#1d2021"
cursor = "#fabd2f"
[colors.selection]
text = "CellForeground"
background = "#504945"
[colors.normal]
black = "#282828"
red = "#cc241d"
green = "#98971a"
yellow = "#d79921"
blue = "#458588"
magenta = "#b16286"
cyan = "#689d6a"
white = "#a89984"
[colors.bright]
black = "#928374"
red = "#fb4934"
green = "#b8bb26"
yellow = "#fabd2f"
blue = "#83a598"
magenta = "#d3869b"
cyan = "#8ec07c"
white = "#ebdbb2"
