# Gruvbox theme layer
set -g status-justify left
set -g message-command-style 'fg=#d79921,bg=#3c3836,align=centre'
set -g window-status-activity-style 'fg=#ebdbb2,bg=#282828,none'
set -g window-status-style 'fg=#ebdbb2,bg=#282828,none'
set -g clock-mode-colour '#458588'
set -g status on
set -g status-position top
set -g status-interval 2
set -g status-bg '#1d2021'
set -g status-fg '#ebdbb2'
set -g status-left-length 30
set -g status-right-length 80
set -g status-left '#[fg=#1d2021,bg=#{?client_prefix,#d3869b,#fabd2f},bold] 󰆍 #S #[default] '
set -g status-right '#[fg=#fabd2f,bold]#{?window_zoomed_flag, ZOOM ,}#[fg=#a89984,nobold] 󰉋 #{b:pane_current_path} '
set -g window-status-separator ''
set -g window-status-format '#[fg=#a89984,bg=#1d2021] #I:#W '
set -g window-status-current-format '#[fg=#1d2021,bg=#83a598,bold] #I:#W '
set -g pane-border-style 'fg=#3c3836'
set -g pane-active-border-style 'fg=#fabd2f'
set -g message-style 'fg=#1d2021,bg=#fabd2f,bold'
set -g mode-style 'fg=#1d2021,bg=#83a598,bold'
